## Deliverable 2. Create a Customer Travel Destinations Map.

In [28]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [29]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Thompson,CA,55.7435,-97.8558,32.16,80,100,8.05,overcast clouds
1,1,Upernavik,GL,72.7868,-56.1549,-2.72,93,87,2.80,overcast clouds
2,2,Dzerzhinsk,RU,56.2389,43.4631,39.02,52,0,4.47,clear sky
3,3,Cabo San Lucas,MX,22.8909,-109.9124,85.60,37,0,3.44,clear sky
4,4,Busselton,AU,-33.6500,115.3333,56.03,81,0,12.15,clear sky

In [30]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 89

In [31]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Cabo San Lucas,MX,22.8909,-109.9124,85.60,37,0,3.44,clear sky
7,7,Hermanus,ZA,-34.4187,19.2345,70.81,88,100,8.66,light rain
8,8,Hamilton,US,39.1834,-84.5333,69.73,76,40,28.77,heavy intensity rain
10,10,Kapaa,US,22.0752,-159.3190,74.19,86,100,17.27,moderate rain
17,17,Campos Altos,BR,-19.6961,-46.1714,70.47,74,100,5.68,overcast clouds
18,18,Camacha,PT,33.0833,-16.3333,60.22,59,40,20.71,scattered clouds
20,20,Santa Rosa,PH,14.3122,121.1114,83.08,83,37,6.64,scattered clouds
21,21,Castro,BR,-24.7911,-50.0119,73.80,69,100,8.39,overcast clouds
25,25,Port Alfred,ZA,-33.5906,26.8910,74.16,72,100,6.24,overcast clouds
26,26,Avarua,CK,-21.2078,-159.7750,78.85,94,40,3.44,scattered clouds

In [32]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                354
City                   354
Country                348
Lat                    354
Lng                    354
Max Temp               354
Humidity               354
Cloudiness             354
Wind Speed             354
Current Description    354
dtype: int64

In [33]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df=preferred_cities_df.dropna()

In [34]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Cabo San Lucas,MX,85.60,clear sky,22.8909,-109.9124,
7,Hermanus,ZA,70.81,light rain,-34.4187,19.2345,
8,Hamilton,US,69.73,heavy intensity rain,39.1834,-84.5333,
10,Kapaa,US,74.19,moderate rain,22.0752,-159.3190,
17,Campos Altos,BR,70.47,overcast clouds,-19.6961,-46.1714,
18,Camacha,PT,60.22,scattered clouds,33.0833,-16.3333,
20,Santa Rosa,PH,83.08,scattered clouds,14.3122,121.1114,
21,Castro,BR,73.80,overcast clouds,-24.7911,-50.0119,
25,Port Alfred,ZA,74.16,overcast clouds,-33.5906,26.8910,
26,Avarua,CK,78.85,scattered clouds,-21.2078,-159.7750,

In [35]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
    # 6c. Get latitude and longitude from DataFrame
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [49]:
# 7. Drop the rows where there is no Hotel Name.
hotel_clean_df = hotel_df.dropna()
hotel_clean_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Cabo San Lucas,MX,85.60,clear sky,22.8909,-109.9124,Hotel Tesoro Los Cabos
7,Hermanus,ZA,70.81,light rain,-34.4187,19.2345,Misty Waves Boutique Hotel
8,Hamilton,US,69.73,heavy intensity rain,39.1834,-84.5333,Six Acres Bed & Breakfast
10,Kapaa,US,74.19,moderate rain,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
17,Campos Altos,BR,70.47,overcast clouds,-19.6961,-46.1714,Hotel São José
...,...,...,...,...,...,...,...
703,Belmonte,BR,80.82,clear sky,-15.8631,-38.8828,Pousada Monte Carmelo O Pão
706,Bathsheba,BB,83.01,few clouds,13.2167,-59.5167,Atlantis Hotel
709,Mattru,SL,83.37,broken clouds,7.6244,-11.8332,"Mondkor Town, Bagbo Chiefdom, Bo District"
711,Bodden Town,KY,87.80,scattered clouds,19.2833,-81.2500,Will T Place
712,Kokoda,PG,73.02,broken clouds,-8.8785,147.7407,Daito Guest House

In [50]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_clean_df.to_csv(output_data_file, index_label="City_ID")

In [52]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City Name</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [53]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))